//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xiaohu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int ID { get; set; }
        public System.DateTime UpDate { get; set; }
        public string FileName { get; set; }
        public string UpUserName { get; set; }
        public string AuditUserName { get; set; }
        public string Format { get; set; }
        public float Approved { get; set; }
        public string Comment { get; set; }
    
        public virtual User User { get; set; }
    }
}
